### ISSUE TITLE
Droping items bug?

### ISSUE THREAD

**Issue by Darius013** [jrbudda/Sentry#151]
Hi, I've equiped an NPC with /npc equip and they drop the items but no one can take them, they're floating there without any sense, I don't know if they're going to disappear or not, but how can I fix this? Thanks!

PD: They have /sentry drop in false.

**Comment by Darius013** [comment]
![ewewweewtt](https://f.cloud.github.com/assets/4774168/867640/cc0b19ec-f719-11e2-828b-fe840a1326cc.png)

**Comment by Dakado** [comment]
Yes,I got exactly the same problem, but the problem is that this issue makes sentry no more usable. Sentry without any equip is like boring and sentry with equip due to this bug is no usable. 
For jrbudda: This bug is causing that NPC has HP, the same problem is in denizen, but you can disable "animated death" in config of denizen, then npc like disappears  instead of die. So can you make that option: animated death: false = npc disappears like and true npc die like a normal player (falling down on the floor). Please look at this, because of that bug are actually sentry no usable for anything....

**Comment by jrbudda** [comment]
Its a client-side issue. It's fixed for the next version of sentry.
