### ISSUE TITLE
Feature Request: Sentries can prioritize enemy engagement over npc pathing

### ISSUE THREAD

**Issue by cjc343** [jrbudda/Sentry#6]
It would be cool if Sentries were able to ignore their path and prioritize engagement of targets when a target has been encountered.

Currently, it appears as though NPCs continue to follow their set path while attempting to attack enemies, prioritizing their pathing over safety and murder.

A stationary sentry, on the other hand, will move to attack and pursue targets it acquires until it can no longer find targets.

Being able to combine these behaviors in a sentry that:
- Engages targets as it follows its path
- Ensures engaged targets are terminated or escape target range prior to continuing along its path, following them if necessary
- Engages any new targets prior to continuing along its path

Would allow users to create more life-like patrol sentries.

**Comment by jrbudda** [comment]
Hmm something is odd there. Melee sentries should leave their path to pursue targets.
Ranged Sentries should stay on their path and fire at targets.

Will check, pathing is done in Citizens core, something may have changed.

**Comment by jrbudda** [comment]
I cannot duplicate your problem, using the latest version of Sentry my melee sentries walk their path til they see a target, they go kill it, and return to their path.

Ranged sentries stay on their path by design.

**Comment by cjc343** [comment]
Sorry, I should have clarified -- I was working with ranged sentries.

Since they continue along their path, targets can be left alive, and others can be run into while more distant targets are still being attacked.

I haven't tested melee sentries with paths -- sounds like they do exactly what I'm looking for.

**Comment by jrbudda** [comment]
Ranged sentries have no idea how to move in relation to a target, they either could stay on their path, or stop in place. Problem with stopping is a target may be impossible to hit with an arrow due to cover. The sentry would then stop and fire at it forever, leaving his patrol route unguarded and the sentry useless. At least on the path they can get some arrows in and hit them again the next time around.

You could try slowing the sentry down with /npc speed so he has more time to shoot. or increase their damage.

Sentries dont look for new targets until their current one is dead, the target finding and the arrow ballistics are both kinda expensive calculations so I only do one or the other. I may add in a check every few seconds to reassess targets even if there is an active one, should keep them from running headlong into a new mob and not attacking it.

Generally speaking melee sentries make better patrolers, and ranged sentries do better up in a tower standing still.

**Comment by cjc343** [comment]
Thanks for the explanation, seems perfectly reasonable and it sounds like I really want melee sentries where I've used ranged ones.
